### ISSUE TITLE
Author attribution in README

### ISSUE THREAD

**Issue by IshanJ25** [Bangik/Bangik#1]
Hi, I am @IshanJ25

I noticed you recently forked one of my repositories, then updated your GitHub profile readme, and it has some of the same code as mine, like the "contribution snake animation"

```yml
    steps:
      - uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snek_dark.svg?palette=github-dark&color_snake=#7878FF
            dist/snek_light.svg?palette=github-light&color_snake=#5050FF
```

```xml
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://github.com/Bangik/Bangik/blob/output/snek_dark.svg">
  <source media="(prefers-color-scheme: light)" srcset="https://github.com/Bangik/Bangik/blob/output/snek_light.svg">
  <img src="https://github.com/Bangik/Bangik/blob/output/snek_dark.svg">
</picture>
```

would you mind giving me attribution for this part of code in your README.md file?
